name: CI
on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: npm run preinstall
      - run: npm run build-backend
      - run: cd awp-assignment-backend && cp package.json package-lock.json dist

      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: awp-assignment-backend/dist

  deploy-backend:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: awp-assignment-backend/dist

      - run: echo "${{ secrets.SSH_KEY }}" > key
      - run: chmod 400 key
      - run: rsync -rav --delete -e "ssh -i key -o StrictHostKeyChecking=no" awp-assignment-backend/dist root@164.90.164.4:~/awp/backend/
      - uses: JimCronqvist/action-ssh@master
        with:
          hosts: "164.90.164.4"
          privateKey: ${{ secrets.SSH_KEY }}
          command: cd /root/awp/backend/dist && npm install
          command: cd /root/awp/backend/dist && pm2 restart index.js
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: npm run install
      - run: npm run build

      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: awp-assignment-frontend/build

  deploy-frontend:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: build
          path: awp-assignment-frontend/build

      - run: echo "${{ secrets.SSH_KEY }}" > key
      - run: chmod 400 key
      - run: rsync -rav --delete -e "ssh -i key -o StrictHostKeyChecking=no" awp-assignment-frontend/build root@164.90.164.4:~/awp/frontend/
